export enum Role {
  ADMIN = 'ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  STUDENT = 'STUDENT',
}

export enum Difficulty {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export enum PrimaryStyle {
  MAMBO_ON2 = 'MAMBO_ON2',
  CASINO = 'CASINO',
  SENSUAL_BACHATA = 'SENSUAL_BACHATA',
}

export enum VideoType {
  STEP_BREAKDOWN = 'STEP_BREAKDOWN',
  COMBINATION = 'COMBINATION',
  FULL_PATTERN = 'FULL_PATTERN',
  SHINES_SEQUENCE = 'SHINES_SEQUENCE',
}